"""
n8n AI Agent Node — Python implementation (provider-agnostic)

Mirrors the n8n AI Agent node:
  - Pluggable AI backend  (OpenAI, Anthropic, Ollama, or any custom provider)
  - API key + per-provider settings stored in one place
  - Tool registration with JSON-schema descriptions (function calling)
  - Swappable memory strategies (none, window buffer, summary)
  - A single .run(prompt) entry point that returns the final text response

Install extras as needed:
  pip install openai            # OpenAI / Azure / Ollama-compatible
  pip install anthropic         # Anthropic Claude
"""

from __future__ import annotations

import json
from abc import ABC, abstractmethod
from copy import deepcopy
from dataclasses import dataclass, field
from typing import Any, Callable


# ---------------------------------------------------------------------------
# Tool
# ---------------------------------------------------------------------------

@dataclass
class Tool:
    """
    A callable tool the agent may invoke.

    Parameters
    ----------
    name:
        Unique identifier used in function-calling payloads.
    description:
        Natural-language description sent to the model.
    parameters:
        JSON-Schema object describing the tool's input arguments.
    fn:
        Python callable that executes the tool and returns a string result.

    Example
    -------
    >>> import datetime
    >>> Tool(
    ...     name="get_date",
    ...     description="Returns today's date.",
    ...     parameters={"type": "object", "properties": {}, "required": []},
    ...     fn=lambda **_: str(datetime.date.today()),
    ... )
    """
    name: str
    description: str
    parameters: dict  # JSON Schema
    fn: Callable[..., str]

    def call(self, arguments: dict) -> str:
        """Execute the tool and return a string result."""
        try:
            result = self.fn(**arguments)
            return str(result)
        except Exception as exc:
            return f"Tool error: {exc}"


# ---------------------------------------------------------------------------
# Memory strategies
# ---------------------------------------------------------------------------

@dataclass
class Message:
    role: str   # "system" | "user" | "assistant" | "tool"
    content: str
    tool_call_id: str | None = None   # for tool-result messages


class BaseMemory(ABC):
    """Abstract memory — stores and retrieves the conversation history."""

    @abstractmethod
    def add(self, message: Message) -> None: ...

    @abstractmethod
    def get(self) -> list[Message]: ...

    @abstractmethod
    def clear(self) -> None: ...


class NoMemory(BaseMemory):
    """Stateless — each run starts fresh (only the current prompt is sent)."""

    def __init__(self) -> None:
        self._pending: list[Message] = []

    def add(self, message: Message) -> None:
        self._pending.append(message)

    def get(self) -> list[Message]:
        msgs = list(self._pending)
        self._pending.clear()
        return msgs

    def clear(self) -> None:
        self._pending.clear()


class WindowBufferMemory(BaseMemory):
    """
    Keeps the last *k* user/assistant turn-pairs.

    Equivalent to n8n's Window Buffer Memory sub-node.
    """

    def __init__(self, window_size: int = 10) -> None:
        self.window_size = window_size
        self._history: list[Message] = []

    def add(self, message: Message) -> None:
        self._history.append(message)
        # Trim to window_size turn-pairs (each pair = 2 messages)
        max_msgs = self.window_size * 2
        if len(self._history) > max_msgs:
            self._history = self._history[-max_msgs:]

    def get(self) -> list[Message]:
        return list(self._history)

    def clear(self) -> None:
        self._history.clear()


class SummaryMemory(BaseMemory):
    """
    Compresses old turns into a rolling summary kept as a system message.

    Equivalent to n8n's Summary Memory sub-node.
    The summary is regenerated by the backend whenever the buffer overflows.
    """

    def __init__(self, max_turns: int = 6) -> None:
        self.max_turns = max_turns
        self._summary: str = ""
        self._recent: list[Message] = []

    # The backend calls this to update the summary when needed
    def set_summary(self, summary: str) -> None:
        self._summary = summary
        self._recent.clear()

    def needs_summarization(self) -> bool:
        return len(self._recent) >= self.max_turns * 2

    def add(self, message: Message) -> None:
        self._recent.append(message)

    def get(self) -> list[Message]:
        msgs: list[Message] = []
        if self._summary:
            msgs.append(Message(role="system", content=f"Conversation so far:\n{self._summary}"))
        msgs.extend(self._recent)
        return msgs

    def clear(self) -> None:
        self._summary = ""
        self._recent.clear()


# ---------------------------------------------------------------------------
# AI Backend (provider abstraction)
# ---------------------------------------------------------------------------

@dataclass
class AISettings:
    """
    Provider-agnostic model settings.

    Any key not consumed by the backend is forwarded verbatim to the API,
    so provider-specific options (e.g. ``top_k``, ``seed``) can be passed
    without modifying this class.
    """
    model: str = "gpt-4o"
    temperature: float = 0.7
    max_tokens: int = 1024
    system_prompt: str = "You are a helpful assistant."
    extra: dict = field(default_factory=dict)


class AIBackend(ABC):
    """
    Abstract AI provider backend.

    Implement this class to add support for any AI provider.
    """

    def __init__(self, api_key: str, settings: AISettings) -> None:
        self.api_key = api_key
        self.settings = settings

    @abstractmethod
    def chat(
        self,
        messages: list[Message],
        tools: list[Tool],
    ) -> tuple[str | None, list[dict] | None]:
        """
        Send messages to the model.

        Returns
        -------
        (text_response, tool_calls)
            Exactly one of the two will be non-None on each call:
            - text_response: the model's final text reply
            - tool_calls: list of {"id": str, "name": str, "arguments": dict}
        """
        ...

    @property
    def provider_name(self) -> str:
        return self.__class__.__name__


# ---------------------------------------------------------------------------
# Concrete backends
# ---------------------------------------------------------------------------

class OpenAIBackend(AIBackend):
    """
    Backend for OpenAI (and OpenAI-compatible APIs: Azure, Ollama, LM Studio …).

    Extra settings
    --------------
    base_url : str
        Override the API base URL (e.g. "http://localhost:11434/v1" for Ollama).
    """

    def __init__(self, api_key: str, settings: AISettings) -> None:
        super().__init__(api_key, settings)
        self._client = None  # lazily initialised on first chat() call

    def _get_client(self):
        if self._client is None:
            try:
                from openai import OpenAI
            except ImportError:
                raise ImportError("pip install openai")
            base_url = self.settings.extra.get("base_url")
            self._client = OpenAI(api_key=self.api_key, base_url=base_url)
        return self._client

    def chat(
        self,
        messages: list[Message],
        tools: list[Tool],
    ) -> tuple[str | None, list[dict] | None]:
        oai_msgs = self._to_oai_messages(messages)
        kwargs: dict[str, Any] = dict(
            model=self.settings.model,
            messages=oai_msgs,
            temperature=self.settings.temperature,
            max_tokens=self.settings.max_tokens,
            **{k: v for k, v in self.settings.extra.items() if k != "base_url"},
        )
        if tools:
            kwargs["tools"] = [self._tool_schema(t) for t in tools]
            kwargs["tool_choice"] = "auto"

        response = self._get_client().chat.completions.create(**kwargs)
        choice = response.choices[0]

        if choice.finish_reason == "tool_calls":
            calls = [
                {
                    "id": tc.id,
                    "name": tc.function.name,
                    "arguments": json.loads(tc.function.arguments),
                }
                for tc in choice.message.tool_calls
            ]
            return None, calls

        return choice.message.content, None

    @staticmethod
    def _to_oai_messages(messages: list[Message]) -> list[dict]:
        out = []
        for m in messages:
            if m.role == "tool":
                out.append({"role": "tool", "tool_call_id": m.tool_call_id, "content": m.content})
            else:
                out.append({"role": m.role, "content": m.content})
        return out

    @staticmethod
    def _tool_schema(tool: Tool) -> dict:
        return {
            "type": "function",
            "function": {
                "name": tool.name,
                "description": tool.description,
                "parameters": tool.parameters,
            },
        }


class AnthropicBackend(AIBackend):
    """
    Backend for Anthropic Claude models.

    Uses Anthropic's tool-use API for function calling.
    """

    def __init__(self, api_key: str, settings: AISettings) -> None:
        super().__init__(api_key, settings)
        self._client = None  # lazily initialised

    def _get_client(self):
        if self._client is None:
            try:
                import anthropic as _anthropic
            except ImportError:
                raise ImportError("pip install anthropic")
            self._client = _anthropic.Anthropic(api_key=self.api_key)
        return self._client

    def chat(
        self,
        messages: list[Message],
        tools: list[Tool],
    ) -> tuple[str | None, list[dict] | None]:
        # Anthropic separates system prompt from the messages array
        system = self.settings.system_prompt
        ant_msgs = [
            {"role": m.role if m.role != "tool" else "user", "content": m.content}
            for m in messages
            if m.role not in ("system",)
        ]

        kwargs: dict[str, Any] = dict(
            model=self.settings.model,
            max_tokens=self.settings.max_tokens,
            system=system,
            messages=ant_msgs,
            **{k: v for k, v in self.settings.extra.items()},
        )
        if tools:
            kwargs["tools"] = [
                {
                    "name": t.name,
                    "description": t.description,
                    "input_schema": t.parameters,
                }
                for t in tools
            ]

        response = self._get_client().messages.create(**kwargs)

        tool_uses = [b for b in response.content if b.type == "tool_use"]
        if tool_uses:
            calls = [
                {"id": b.id, "name": b.name, "arguments": b.input}
                for b in tool_uses
            ]
            return None, calls

        text_blocks = [b for b in response.content if b.type == "text"]
        return text_blocks[0].text if text_blocks else "", None


class OllamaBackend(OpenAIBackend):
    """
    Backend for local Ollama models (uses the OpenAI-compatible endpoint).

    Defaults to http://localhost:11434/v1 with no API key required.
    """

    def __init__(self, api_key: str = "ollama", settings: AISettings | None = None) -> None:
        if settings is None:
            settings = AISettings(model="llama3")
        settings.extra.setdefault("base_url", "http://localhost:11434/v1")
        super().__init__(api_key, settings)


# ---------------------------------------------------------------------------
# Registry — map provider name → backend class
# ---------------------------------------------------------------------------

_BACKEND_REGISTRY: dict[str, type[AIBackend]] = {
    "openai": OpenAIBackend,
    "anthropic": AnthropicBackend,
    "ollama": OllamaBackend,
}


def register_backend(name: str, cls: type[AIBackend]) -> None:
    """Register a custom backend so it can be referenced by name."""
    _BACKEND_REGISTRY[name.lower()] = cls


# ---------------------------------------------------------------------------
# AI Agent Node
# ---------------------------------------------------------------------------

class AIAgentNode:
    """
    Provider-agnostic AI Agent node.

    Mirrors n8n's AI Agent node: a model backend + tools + memory wired
    together into a single .run(prompt) call.

    Parameters
    ----------
    provider:
        One of "openai", "anthropic", "ollama", or a name registered via
        register_backend().
    api_key:
        API key for the chosen provider.
    settings:
        AISettings instance controlling model, temperature, system prompt, etc.
    memory:
        A BaseMemory instance. Defaults to WindowBufferMemory(window_size=10).
    max_iterations:
        Guard against infinite tool-call loops (default 10).

    Example
    -------
    >>> agent = AIAgentNode(
    ...     provider="openai",
    ...     api_key="sk-...",
    ...     settings=AISettings(model="gpt-4o", temperature=0.3),
    ... )
    >>> agent.add_tool(my_tool)
    >>> print(agent.run("What's 2 + 2?"))
    """

    def __init__(
        self,
        provider: str,
        api_key: str,
        settings: AISettings | None = None,
        memory: BaseMemory | None = None,
        max_iterations: int = 10,
    ) -> None:
        self.settings = settings or AISettings()
        self.memory = memory or WindowBufferMemory()
        self.max_iterations = max_iterations
        self._tools: dict[str, Tool] = {}

        backend_cls = _BACKEND_REGISTRY.get(provider.lower())
        if backend_cls is None:
            raise ValueError(
                f"Unknown provider '{provider}'. "
                f"Available: {list(_BACKEND_REGISTRY)}. "
                "Use register_backend() to add a custom provider."
            )
        self.backend: AIBackend = backend_cls(api_key, self.settings)

    # ------------------------------------------------------------------
    # Tool management
    # ------------------------------------------------------------------

    def add_tool(self, tool: Tool) -> None:
        """Register a tool the agent can call."""
        self._tools[tool.name] = tool

    def remove_tool(self, name: str) -> None:
        """Unregister a tool by name."""
        self._tools.pop(name, None)

    @property
    def tools(self) -> list[Tool]:
        return list(self._tools.values())

    # ------------------------------------------------------------------
    # Memory management
    # ------------------------------------------------------------------

    def set_memory(self, memory: BaseMemory) -> None:
        """Swap the memory strategy at runtime."""
        self.memory = memory

    def clear_memory(self) -> None:
        """Reset conversation history."""
        self.memory.clear()

    # ------------------------------------------------------------------
    # Core run loop (ReAct-style: think → act → observe → repeat)
    # ------------------------------------------------------------------

    def run(self, prompt: str) -> str:
        """
        Process a user prompt and return the agent's final text response.

        The agent will call tools as needed (up to max_iterations) before
        returning its final answer.
        """
        # Build the full message list: system + history + new user message
        system_msg = Message(role="system", content=self.settings.system_prompt)
        user_msg = Message(role="user", content=prompt)

        self.memory.add(user_msg)

        for _ in range(self.max_iterations):
            messages = [system_msg] + self.memory.get()

            text, tool_calls = self.backend.chat(messages, self.tools)

            # Model returned a final text answer
            if text is not None:
                assistant_msg = Message(role="assistant", content=text)
                self.memory.add(assistant_msg)

                # SummaryMemory: compress if the buffer is full
                if (
                    isinstance(self.memory, SummaryMemory)
                    and self.memory.needs_summarization()
                ):
                    summary_prompt = (
                        "Summarize the conversation so far in a few sentences, "
                        "preserving key facts and decisions."
                    )
                    summary, _ = self.backend.chat(
                        [system_msg] + self.memory.get() + [Message(role="user", content=summary_prompt)],
                        [],
                    )
                    self.memory.set_summary(summary or "")

                return text

            # Model wants to call one or more tools
            for call in (tool_calls or []):
                tool = self._tools.get(call["name"])
                result = tool.call(call["arguments"]) if tool else f"Unknown tool: {call['name']}"

                # Record tool invocation + result in memory
                self.memory.add(
                    Message(role="assistant", content=f"[tool_call:{call['name']}] {json.dumps(call['arguments'])}")
                )
                self.memory.add(
                    Message(role="tool", content=result, tool_call_id=call.get("id"))
                )

        return "Max iterations reached without a final answer."

    # ------------------------------------------------------------------
    # Info
    # ------------------------------------------------------------------

    def __repr__(self) -> str:
        return (
            f"AIAgentNode(provider={self.backend.provider_name}, "
            f"model={self.settings.model}, "
            f"tools={list(self._tools)}, "
            f"memory={type(self.memory).__name__})"
        )


# ---------------------------------------------------------------------------
# Quick demo (no real API key needed — shows wiring only)
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import datetime

    # --- Define tools ---
    date_tool = Tool(
        name="get_current_date",
        description="Returns today's date in ISO format.",
        parameters={"type": "object", "properties": {}, "required": []},
        fn=lambda: str(datetime.date.today()),
    )

    calculator_tool = Tool(
        name="calculate",
        description="Evaluate a simple arithmetic expression and return the result.",
        parameters={
            "type": "object",
            "properties": {
                "expression": {
                    "type": "string",
                    "description": "A Python arithmetic expression, e.g. '2 + 2' or '10 * 3.5'",
                }
            },
            "required": ["expression"],
        },
        fn=lambda expression: str(eval(expression, {"__builtins__": {}}, {})),  # noqa: S307
    )

    # --- Build agent (OpenAI backend, window memory) ---
    agent = AIAgentNode(
        provider="openai",
        api_key="sk-YOUR_KEY_HERE",          # <-- replace to run live
        settings=AISettings(
            model="gpt-4o-mini",
            temperature=0.2,
            max_tokens=512,
            system_prompt="You are a concise assistant. Use tools when helpful.",
            extra={"seed": 42},              # provider-specific extras
        ),
        memory=WindowBufferMemory(window_size=5),
        max_iterations=8,
    )

    agent.add_tool(date_tool)
    agent.add_tool(calculator_tool)

    print(agent)
    print("\nTools registered:", [t.name for t in agent.tools])
    print("\n--- Switching to Anthropic backend example ---")

    # Same config, different provider — just change provider= and api_key=
    claude_agent = AIAgentNode(
        provider="anthropic",
        api_key="sk-ant-YOUR_KEY_HERE",
        settings=AISettings(
            model="claude-sonnet-4-6",
            temperature=0.5,
            system_prompt="You are a helpful assistant.",
        ),
        memory=SummaryMemory(max_turns=4),
    )
    claude_agent.add_tool(date_tool)
    print(claude_agent)

    print("\n--- Ollama (local, no key needed) ---")
    ollama_agent = AIAgentNode(
        provider="ollama",
        api_key="ollama",
        settings=AISettings(model="llama3", temperature=0.7),
        memory=NoMemory(),
    )
    ollama_agent.add_tool(calculator_tool)
    print(ollama_agent)

    print("\nAll agents constructed successfully.")
    print("Set a real API key and call agent.run('your prompt') to execute.")
